"""chat usage and token budget

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17 11:50:23.516090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_token_budgets',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('consumed_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('chat_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('retrieval_ms', sa.Float(), nullable=True),
    sa.Column('generation_ms', sa.Float(), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('budget_day', sa.String(length=10), nullable=True),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('charged_tokens', sa.Integer(), nullable=False),
    sa.Column('reservation_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_requests_actor_id'), 'chat_requests', ['actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_requests_actor_id'), table_name='chat_requests')
    op.drop_table('chat_requests')
    op.drop_table('daily_token_budgets')
    # ### end Alembic commands ###
